---

- hosts: "{{ service }}"
  user: root
  #any_errors_fatal: true
  gather_facts: yes
  serial: 1
  vars:
    - service: ag-chain-cosmos
    - data: "{{ SETUP_HOME }}/{{ service }}/data"
    - CHAIN_NAME: "{{ lookup('file', SETUP_HOME + '/' + service + '/chain-name.txt') }}"
    - STAKER: ag-staker
    - STAKER_NODE: node0
    - STAKER_AMOUNT: 2000000stake
  roles:
    - cosmos-validators
