---

- hosts: "{{ service }}"
  user: root
  #any_errors_fatal: true
  gather_facts: yes
  strategy: free
  vars:
    - service: ag-pserver
    - data: "{{ SETUP_HOME }}/{{ service }}/data"
    - GCI: "{{ lookup('file', SETUP_HOME + '/' + service + '/gci.txt') }}"
    - RPC_ADDRS: "{{ lookup('file', SETUP_HOME + '/' + service + '/rpcaddrs.txt') }}"
    - CHAIN_NAME: "{{ lookup('file', SETUP_HOME + '/ag-chain-cosmos/chain-name.txt') }}"
    - NETWORK_NAME: "{{ lookup('file', SETUP_HOME + '/network.txt') }}"
  roles:
    - stat-tls-keys
    - install-controller
