
- name: "check if {{ NETWORK_NAME }}.key exists"
  delegate_to: localhost
  stat:
    path: "{{ SETUP_HOME }}/{{ NETWORK_NAME }}.key"
  register: "tlskey"

- name: "check if {{ NETWORK_NAME }}.crt exists"
  delegate_to: localhost
  stat:
    path: "{{ SETUP_HOME }}/{{ NETWORK_NAME }}.crt"
  register: "tlscrt"

