- name: "Initialize {{ service }}"
  become: yes
  become_user: "{{ service }}"
  shell: "{{ service }} init {{ inventory_hostname }} --chain-id={{ CHAIN_NAME }}"

#- name: "Add coins to {{ service }}"
#  become: yes
#  become_user: "{{ service }}"
#  shell: "{{ service }} add-genesis-account {{ BOOTSTRAP_ADDRESS }} {{ BOOTSTRAP_TOKENS }}"
