- name: Download nodesource PPA
  get_url:
    url: "https://deb.nodesource.com/setup_{{ NODEJS_VERSION }}.x"
    dest: "/root/setup_nodejs{{ NODEJS_VERSION }}.sh"
    mode: "0755"

- name: Install nodesource PPA
  shell: "/root/setup_nodejs{{ NODEJS_VERSION }}.sh"

- name: Update repositories cache and install prerequisites
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
    - rsync
    - sudo
    - curl
    - xfsprogs
    - "nodejs={{ NODEJS_VERSION }}.*"

- name: Stat /dev/sda
  stat:
    path: /dev/sda
  register: sda

- name: Resize /dev/sda with XFS
  filesystem:
    fstype: xfs
    dev: /dev/sda
    resizefs: yes
  when: sda.stat.exists

- name: Mount /dev/sda
  mount:
    path: /home
    src: /dev/sda
    fstype: auto
    state: mounted
  when: sda.stat.exists
