name: Test all Packages

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # 'yarn install' must be done at the top level, to build all the
    # cross-package symlinks
    - name: yarn install
      run: yarn install
    # 'yarn build' loops over all workspaces
    - name: yarn build
      run: yarn build
    # We run separate steps for each package, to make it easier to drill down
    # into errors. If we wanted to just run everything, run 'yarn test' from
    # the top level.
    #- name: yarn test (everything)
    #  run: yarn test
    - name: yarn test (acorn-eventual-send)
      run: cd packages/acorn-eventual-send && yarn test
    - name: yarn test (eventual-send)
      run: cd packages/eventual-send && yarn test
    - name: yarn test (transform-eventual-send)
      run: cd packages/transform-eventual-send && yarn test
    - name: yarn test (default-evaluate-options)
      run: cd packages/default-evaluate-options && yarn test
    - name: yarn test (evaluate)
      run: cd packages/evaluate && yarn test
    - name: yarn test (bundle-source)
      run: cd packages/bundle-source && yarn test
    - name: yarn test (marshal)
      run: cd packages/marshal && yarn test
    - name: yarn test (captp)
      run: cd packages/captp && yarn test
    - name: yarn test (SwingSet)
      run: cd packages/SwingSet && yarn test
    - name: yarn test (ERTP)
      run: cd packages/ERTP && yarn test
    - name: yarn test (cosmic-swingset)
      run: cd packages/cosmic-swingset && yarn test
    - name: yarn test (agoric-cli)
      run: cd packages/agoric-cli && yarn test
    - name: lint check (marshal, SwingSet, ERTP)
      run: yarn lint-check
    - name: yarn test (zoe)
      run: cd packages/zoe && yarn test
